### ISSUE TITLE
Usage of replication mode in the Python wrapper

### ISSUE THREAD

**Issue by metalshanked** [slingdata-io/sling-python#12]
Hi,
I wanted to use the Replication json that i use for `sling run -r /path/to/replication.json` in the python wrapper.
I seem to be getting errors when trying the below approach.
Using sling `1.1.5.post1` from Pypi

```
from sling import Replication, ReplicationStream

default_config = ReplicationStream(**defaults) #Defaults is dict of configs
streams_config = ReplicationStream(**streams) #streams is dict of stream configs
Replication(source='SLING_SOURCE_CONN', target='SLING_TARGET_CONN', defaults=default_config,streams=streams_config,debug=True).run()   
```

`AttributeError: 'Replication' object has no attribute 'replication'` , `AttributeError: 'str' object has no attribute 'conn'`

Any advise on the correct usage for Replication streams?
Is there a way to just use the same JSON that we use for `sling run -r /path/to/replication.json` in the python wrapper?

**Comment by flarco** [comment]
Can you try again? Just released `1.1.5.post2`.

**Comment by flarco** [comment]
For using an existing json file, I think you could just do 

```python

with open('/path/to/replication.json') as file:
  data = json.load(file)
r = Replication(**data)
r.run()
```

**Comment by metalshanked** [comment]
Thanks @flarco! It is working now!
Will test further and revert.

**Comment by metalshanked** [comment]
Thanks @flarco! It is working now!
Will test further and revert.
