### ISSUE TITLE
Umlaut in first row of CSV file not imported correctly

### ISSUE THREAD

**Issue by SebastianArcq** [slingdata-io/sling-python#15]
There is a bug that causes Umlauts (such as the German "ö") in csv-files to not be properly encoded when imported to Snowflake - but only the very first row! All subsequent rows work fine.

Please find a sample file [bug_demo.csv](https://github.com/slingdata-io/sling-python/files/14498121/bug_demo.csv) attached.

Here is what the file looks like on my machine:
![Screenshot 2024-03-05 at 17 06 29](https://github.com/slingdata-io/sling-python/assets/89322283/0f14a1ca-4e45-4d4e-aed9-946af4742507)

Here's the code I use to import the file:
```
from sling import Sling

def sling_to_snowflake(source):
    config = {
        "source": {
            "stream": source,
            "options": {
                "format": "csv",
                "delimiter": ";",
                "columns": {
                    "*": "string",
                },
                "transforms": ["decode_windows1252"]
            }
        },
        "target": {
            "conn":  "snowflake_connection",
            "object": "sts.bug_demo"
        },
        "mode": "full-refresh"
    }

    Sling(**config).run()

fileLocation = 'file:///link/to/my/csv/file/bug_demo.csv'

sling_to_snowflake(fileLocation)
```

This is what it will look like in Snowflake:
![Screenshot 2024-03-05 at 16 58 19](https://github.com/slingdata-io/sling-python/assets/89322283/009df43c-2d46-4a1a-9277-ea0009da9355)

**Comment by flarco** [comment]
Thanks for the sample file, will look into it.

**Comment by SebastianArcq** [comment]
Cool. Let me know if I can help you in any way.
