### ISSUE TITLE
Sources passed via env kwarg to Replication are not respected

### ISSUE THREAD

**Issue by pSpitzner** [slingdata-io/sling-python#21]
Sources can be set via environment variables, which is handy for a quick one-off transfer.

In python, this can be done, and works as expected, when using the os module:

```python
import os
os.environ["DB_SOURCE"] = connection_string
```

The `sling.Replication` initializer also takes an `env` variable,  which one would expect to work analogeously (but avoids polluting the global name space)

However, sling does not find the source when configured via the this kwarg:

```python
replication = sling.Replication(
    source="DB_SOURCE",
    target="LOCAL",
    env=dict(
        # the local environment variable is not sufficient 
        DB_SOURCE=connection_string,
        SLING_STREAM_URL_COLUMN="true",
        SLING_LOADED_AT_COLUMN="true",
    ),
    streams=streams,
)
```
I checked the config that is created from the python side on disk ([`__init__.py`](https://github.com/slingdata-io/sling-python/blob/ea3fca591bf501245a98d826b42586d47aefb648/sling/sling/__init__.py#L343)), and the writing to disk works as expected. Thus, I assume this to be an issue related to the sling backend, not the python wrapper.

Tested on windows.

Minimal working example:

```python
import os
import sling

def replicate_to_parquet(
    connection_string: str,
    table_name: str,
    target_path: str,
    primary_key: str | None = None,
    mode: str = "full-refresh",
    stream_kwargs: dict = None,
    replication_kwargs: dict = None,
):
    """
    Use sling to replicate a table from a database to a parquet file.

    Example
    -------
    ```
    replicate_to_parquet(
        connection_string="sqlserver://localhost?database=WideWorldImporters",
        table_name="Sales.CustomerTransactions",
        target_path="./Sales.CustomerTransactions.parquet",
    )
    ```
    """

    # with globally set environment variable, it works.
    # os.environ["DB_SOURCE"] = connection_string

    streams = {}
    streams[table_name] = sling.ReplicationStream(
        mode=mode,
        object=os.path.abspath(target_path),
        primary_key=primary_key,
        target_options=sling.TargetOptions(
            format="parquet"
        ),
        **(stream_kwargs or {})
    )

    replication = sling.Replication(
        source="DB_SOURCE",
        target="LOCAL",
        env=dict(
            # but the local environment variable is not sufficient 
            DB_SOURCE=connection_string,
            SLING_STREAM_URL_COLUMN="true",
            SLING_LOADED_AT_COLUMN="true",
        ),
        streams=streams,
        **(replication_kwargs or {})
    )

    replication.run()

replicate_to_parquet(
    connection_string="sqlserver://localhost?database=WideWorldImporters",
    table_name="Sales.CustomerTransactions",
    target_path="./Sales.CustomerTransactions.parquet",
)
```

**Comment by flarco** [comment]
Do you mind opening a PR?

**Comment by pSpitzner** [comment]
Sure thing, I will dig a bit deeper. It seems that we already parse an env dict to `Popen`, I would expect that to be sufficient.
