### ISSUE TITLE
Unset `env` creates `AttributeError` on `sling.run()`

### ISSUE THREAD

**Issue by BFreeNashville** [slingdata-io/sling-python#4]
When using the `run` method, if the `env` arg is not set an `AttributeError` occurs. 

The issue can be shown with  the following snippet:

```
import os

env = None

for k, v in os.environ.items():
    env[k] = env.get(k, v)
```

Since there is no method `get` on `NoneType` the attribute error is raised.

**Comment by flarco** [comment]
Thanks, fixed with https://github.com/slingdata-io/sling-python/commit/628d47738d84450a6f23e7a4b6efff336fb8884f.
About to release new version
