### ISSUE TITLE
Install different binary data files based on the platform

### ISSUE THREAD

**Issue by guaripete-github** [slingdata-io/sling-python#8]
Current package installs all binaries regardless of platform. In a Linux container, `sling-mac` and `sling-win.exe` amounts to 318 MB of unnecessary data transfer and storage.

Looks like it might be possible to have platform awareness upon installation:
- https://stackoverflow.com/questions/7606776/pythons-setup-py-how-to-install-different-files-for-different-platforms
- https://setuptools.pypa.io/en/latest/userguide/datafiles.html#data-files-support

**Comment by flarco** [comment]
Thanks, I’ve wondered about that. Will look into it.

**Comment by flarco** [comment]
Done, see https://github.com/slingdata-io/sling-python/blob/main/sling/sling/__init__.py#L7-L29
